# -*- coding: utf-8 -*-

SpanishIrregularVerbs = {
  'andar' => :ar_andar,
  'desandar' => :ar_andar,
  
  
  'acertar' => :ar_e_ie,
  'acrecentar' => :ar_e_ie,
  'aferrar' => :ar_e_ie,
  'alentar' => :ar_e_ie,
  'apacentar' => :ar_e_ie,
  'apretar' => :ar_e_ie,
  'arrendar' => :ar_e_ie,
  'asentar' => :ar_e_ie,
  'asestar' => :ar_e_ie,
  'atentar' => :ar_e_ie,
  'aterrar' => :ar_e_ie,
  'atestar' => :ar_e_ie,
  'atravesar' => :ar_e_ie,
  'calentar' => :ar_e_ie,
  'cerrar' => :ar_e_ie,
  'cimentar' => :ar_e_ie,
  'concertar' => :ar_e_ie,
  'confesar' => :ar_e_ie,
  'desacertar' => :ar_e_ie,
  'desalentar' => :ar_e_ie,
  'desconcertar' => :ar_e_ie,
  'desenterrar' => :ar_e_ie,
  'deshelar' => :ar_e_ie,
  'desmembrar' => :ar_e_ie,
  'despertar' => :ar_e_ie,
  'despertarse' => :ar_e_ie,
  'desterrar' => :ar_e_ie,
  'emparentar' => :ar_e_ie,
  'empedrar' => :ar_e_ie,
  'emperrar' => :ar_e_ie,
  'encerrar' => :ar_e_ie,
  'encomendar' => :ar_e_ie,
  'enmendar' => :ar_e_ie,
  'ensangrentar' => :ar_e_ie,
  'enterrar' => :ar_e_ie,
  'escarmentar' => :ar_e_ie,
  'gobernar' => :ar_e_ie,
  'hacendar' => :ar_e_ie,
  'helar' => :ar_e_ie,
  'herrar' => :ar_e_ie,
  'invernar' => :ar_e_ie,
  'manifestar' => :ar_e_ie,
  'mentar' => :ar_e_ie,
  'merendar' => :ar_e_ie,
  'nevar' => :ar_e_ie,
  'pensar' => :ar_e_ie,
  'precalentar' => :ar_e_ie,
  'quebrar' => :ar_e_ie,
  'recalentar' => :ar_e_ie,
  'recomendar' => :ar_e_ie,
  'remendar' => :ar_e_ie,
  'repensar' => :ar_e_ie,
  'reventar' => :ar_e_ie,
  'sarmentar' => :ar_e_ie,
  'sembrar' => :ar_e_ie,
  'sentar' => :ar_e_ie,
  'sentarse' => :ar_e_ie,
  'serrar' => :ar_e_ie,
  'sobrecalentar' => :ar_e_ie,
  'soterrar' => :ar_e_ie,
  'subarrendar' => :ar_e_ie,
  'temblar' => :ar_e_ie,
  'tentar' => :ar_e_ie,
  'ventar' => :ar_e_ie,
	
	
	'agorar' => :ar_go_güe,
  'degollar' => :ar_go_güe,
  
  
  'desosar' => :ar_o_hue,
  
  
  'acordar' => :ar_o_ue,
	'acordarse' => :ar_o_ue,
	'acostar' => :ar_o_ue,
	'acostarse' => :ar_o_ue,
	'amoblar' => :ar_o_ue,
	'apostar' => :ar_o_ue,
	'aprobar' => :ar_o_ue,
	'asolar' => :ar_o_ue,
	'colar' => :ar_o_ue,
	'comprobar' => :ar_o_ue,
	'concordar' => :ar_o_ue,
	'consolar' => :ar_o_ue,
	'contar' => :ar_o_ue,
	'costar' => :ar_o_ue,
	'demostrar' => :ar_o_ue,
	'denostar' => :ar_o_ue,
	'desaprobar' => :ar_o_ue,
	'descollar' => :ar_o_ue,
	'descontar' => :ar_o_ue,
	'desolar' => :ar_o_ue,
	'dolar' => :ar_o_ue,
	'encontrar' => :ar_o_ue,
	'engrosar' => :ar_o_ue,
	'hollar' => :ar_o_ue,
	'mostrar' => :ar_o_ue,
	'poblar' => :ar_o_ue,
	'probar' => :ar_o_ue,
	'recontar' => :ar_o_ue,
	'recordar' => :ar_o_ue,
	'recostar' => :ar_o_ue,
	'renovar' => :ar_o_ue,
	'repoblar' => :ar_o_ue,
	'reprobar' => :ar_o_ue,
	'resollar' => :ar_o_ue,
	'resonar' => :ar_o_ue,
	'rodar' => :ar_o_ue,
	'solar' => :ar_o_ue,
	'soldar' => :ar_o_ue,
	'soltar' => :ar_o_ue,
	'sonar' => :ar_o_ue,
	'soñar' => :ar_o_ue,
	'tostar' => :ar_o_ue,
	'tronar' => :ar_o_ue,
	'volar' => :ar_o_ue,
	'pringar' => :ar_o_ue,
	
	
	'abanicar' => :car,
	'abarcar' => :car,
	'abarracar' => :car,
	'abdicar' => :car,
	'abocar' => :car,
	'abroncar' => :car,
	'acercar' => :car,
	'acercarse' => :car,
	'achacar' => :car,
	'achicar' => :car,
	'achicarse' => :car,
	'acidificar' => :car,
	'acurrucar' => :car,
	'acurrucarse' => :car,
	'adjudicar' => :car,
	'afincar' => :car,
	'ahorcar' => :car,
	'ahuecar' => :car,
	'alambicar' => :car,
	'alocar' => :car,
	'amplificar' => :car,
	'apalancar' => :car,
	'aparcar' => :car,
	'aplacar' => :car,
	'aplicar' => :car,
	'aplicarse' => :car,
	'apriscar' => :car,
	'arrancar' => :car,
	'atacar' => :car,
	'atascar' => :car,
	'atascarse' => :car,
	'atracar' => :car,
	'atrancar' => :car,
	'autenticar' => :car,
	'autentificar' => :car,
	'beatificar' => :car,
	'becar' => :car,
	'bifurcarse' => :car,
	'bisecar' => :car,
	'brincar' => :car,
	'buscar' => :car,
	'caducar' => :car,
	'calcar' => :car,
	'calificar' => :car,
	'cascar' => :car,
	'cercar' => :car,
	'certificar' => :car,
	'chamuscar' => :car,
	'chascar' => :car,
	'chocar' => :car,
	'clarificar' => :car,
	'clasificar' => :car,
	'clasificarse' => :car,
	'codificar' => :car,
	'colocar' => :car,
	'comiscar' => :car,
	'complicar' => :car,
	'comunicar' => :car,
	'confiscar' => :car,
	'contraatacar' => :car,
	'contraindicar' => :car,
	'convocar' => :car,
	'criticar' => :car,
	'crucificar' => :car,
	'cuadruplicar' => :car,
	'cualificar' => :car,
	'cubicar' => :car,
	'decodificar' => :car,
	'dedicar' => :car,
	'dedicarse' => :car,
	'defecar' => :car,
	'deificar' => :car,
	'derrocar' => :car,
	'descalificar' => :car,
	'desembarcar' => :car,
	'desembocar' => :car,
	'desempacar' => :car,
	'desertificar' => :car,
	'desintoxicar' => :car,
	'desmitificar' => :car,
	'destacar' => :car,
	'destocar' => :car,
	'desturcar' => :car,
	'diagnosticar' => :car,
	'discar' => :car,
	'disecar' => :car,
	'dislocar' => :car,
	'diversificar' => :car,
	'domesticar' => :car,
	'dulcificar' => :car,
	'duplicar' => :car,
	'edificar' => :car,
	'educar' => :car,
	'electrificar' => :car,
	'embarcar' => :car,
	'embarrancar' => :car,
	'emboscar' => :car,
	'empacar' => :car,
	'empacarse' => :car,
	'enflacar' => :car,
	'enfocar' => :car,
	'enfrascar' => :car,
	'enfrascarse' => :car,
	'enmarcar' => :car,
	'enrocar' => :car,
	'equivocar' => :car,
	'equivocarse' => :car,
	'erradicar' => :car,
	'escenificar' => :car,
	'especificar' => :car,
	'estacar' => :car,
	'estancar' => :car,
	'estancarse' => :car,
	'evocar' => :car,
	'explicar' => :car,
	'fabricar' => :car,
	'falsificar' => :car,
	'ficar' => :car,
	'fornicar' => :car,
	'fortificar' => :car,
	'fructificar' => :car,
	'gasificar' => :car,
	'gelificarse' => :car,
	'glorificar' => :car,
	'gratificar' => :car,
	'hincar' => :car,
	'identificar' => :car,
	'implicar' => :car,
	'incomunicar' => :car,
	'inculcar' => :car,
	'indicar' => :car,
	'intensificar' => :car,
	'intoxicar' => :car,
	'intricar' => :car,
	'intrincar' => :car,
	'invocar' => :car,
	'justificar' => :car,
	'lubricar' => :car,
	'lubrificar' => :car,
	'machacar' => :car,
	'machucar' => :car,
	'marcar' => :car,
	'mascar' => :car,
	'masticar' => :car,
	'medicar' => :car,
	'mitificar' => :car,
	'modificar' => :car,
	'mortificar' => :car,
	'multiplicar' => :car,
	'neviscar' => :car,
	'nidificar' => :car,
	'notificar' => :car,
	'ofuscar' => :car,
	'pacificar' => :car,
	'pecar' => :car,
	'pellizcar' => :car,
	'perjudicar' => :car,
	'personificar' => :car,
	'pescar' => :car,
	'picar' => :car,
	'planificar' => :car,
	'plastificar' => :car,
	'platicar' => :car,
	'practicar' => :car,
	'predicar' => :car,
	'pronosticar' => :car,
	'provocar' => :car,
	'publicar' => :car,
	'purificar' => :car,
	'radicar' => :car,
	'ramificar' => :car,
	'rascar' => :car,
	'ratificar' => :car,
	'rebuscar' => :car,
	'recalcar' => :car,
	'rectificar' => :car,
	'refrescar' => :car,
	'reivindicar' => :car,
	'remolcar' => :car,
	'repicar' => :car,
	'replicar' => :car,
	'resecar' => :car,
	'reunificar' => :car,
	'revocar' => :car,
	'roncar' => :car,
	'sacar' => :car,
	'sacrificar' => :car,
	'salpicar' => :car,
	'santificar' => :car,
	'saponificar' => :car,
	'secar' => :car,
	'secarse' => :car,
	'significar' => :car,
	'simplificar' => :car,
	'sofocar' => :car,
	'solidificar' => :car,
	'sonsacar' => :car,
	'suplicar' => :car,
	'surcar' => :car,
	'testificar' => :car,
	'opacar' => :car,
	'petrificar' => :car,
	'pizcar' => :car,
	'ramificarse' => :car,
	'tocar' => :car,
	
	
	'convencer' => :cer,
	'ejercer' => :cer,
	'mecer' => :cer,
	'vencer' => :cer,
	
	
	'escocer' => :cer_o_ue,
	'cocer' => :cer_o_ue,
	
	
	'esparcir' => :cir,
	'fruncir' => :cir,
	'resarcir' => :cir,
	'surcir' => :cir,
	'uncir' => :cir,
	'zurcir' => :cir,
	
	
	'dar' => :ar_dar,
	
	
	'abducir' => :ducir,
	'aducir' => :ducir,
	'conducir' => :ducir,
	'coproducir' => :ducir,
	'deducir' => :ducir,
	'educir' => :ducir,
	'inducir' => :ducir,
	'introducir' => :ducir,
	'producir' => :ducir,
	'reducir' => :ducir,
	'reproducir' => :ducir,
	'retraducir' => :ducir,
	'seducir' => :ducir,
	'traducir' => :ducir,
	
	
	'atardecer' => :er_atardecer,
	
	
	'abastecer' => :er_c_zc,
	'aborrecer' => :er_c_zc,
	'acaecer' => :er_c_zc,
	'acontecer' => :er_c_zc,
	'adolecer' => :er_c_zc,
	'adormecer' => :er_c_zc,
	'agradecer' => :er_c_zc,
	'amanecer' => :er_c_zc,
	'anochecer' => :er_c_zc,
	'aparecer' => :er_c_zc,
	'apetecer' => :er_c_zc,
	'autoabastecerse' => :er_c_zc,
	'carecer' => :er_c_zc,
	'compadecer' => :er_c_zc,
	'comparecer' => :er_c_zc,
	'conocer' => :er_c_zc,
	'crecer' => :er_c_zc,
	'decrecer' => :er_c_zc,
	'desagradecer' => :er_c_zc,
	'desaparecer' => :er_c_zc,
	'desconocer' => :er_c_zc,
	'desentumecer' => :er_c_zc,
	'desfallecer' => :er_c_zc,
	'desfavorecer' => :er_c_zc,
	'desmerecer' => :er_c_zc,
	'desobedecer' => :er_c_zc,
	'desvanecer' => :er_c_zc,
	'embellecer' => :er_c_zc,
	'embrutecer' => :er_c_zc,
	'empobrecer' => :er_c_zc,
	'empodrecer' => :er_c_zc,
	'enaltecer' => :er_c_zc,
	'enardecer' => :er_c_zc,
	'encarecer' => :er_c_zc,
	'endurecer' => :er_c_zc,
	'enflaquecer' => :er_c_zc,
	'enfurecer' => :er_c_zc,
	'enloquecer' => :er_c_zc,
	'enloquecerse' => :er_c_zc,
	'enmohecer' => :er_c_zc,
	'enmudecer' => :er_c_zc,
	'ennegrecer' => :er_c_zc,
	'ennoblecer' => :er_c_zc,
	'enorgullecer' => :er_c_zc,
	'enriquecer' => :er_c_zc,
	'enrojecer' => :er_c_zc,
	'ensombrecer' => :er_c_zc,
	'ensordecer' => :er_c_zc,
	'enternecer' => :er_c_zc,
	'entorpecer' => :er_c_zc,
	'entristecer' => :er_c_zc,
	'envejecer' => :er_c_zc,
	'envejecerse' => :er_c_zc,
	'enyegüecer' => :er_c_zc,
	'esclarecer' => :er_c_zc,
	'establecer' => :er_c_zc,
	'estremecer' => :er_c_zc,
	'fallecer' => :er_c_zc,
	'favorecer' => :er_c_zc,
	'fenecer' => :er_c_zc,
	'florecer' => :er_c_zc,
	'fortalecer' => :er_c_zc,
	'fosforecer' => :er_c_zc,
	'guarecer' => :er_c_zc,
	'guarnecer' => :er_c_zc,
	'humedecer' => :er_c_zc,
	'languidecer' => :er_c_zc,
	'merecer' => :er_c_zc,
	'nacer' => :er_c_zc,
	'negrecer' => :er_c_zc,
	'obedecer' => :er_c_zc,
	'ofrecer' => :er_c_zc,
	'oscurecer' => :er_c_zc,
	'pacer' => :er_c_zc,
	'padecer' => :er_c_zc,
	'palidecer' => :er_c_zc,
	'parecer' => :er_c_zc,
	'parecerse' => :er_c_zc,
	'perecer' => :er_c_zc,
	'permanecer' => :er_c_zc,
	'pertenecer' => :er_c_zc,
	'pertenecerse' => :er_c_zc,
	'prevalecer' => :er_c_zc,
	'reaparecer' => :er_c_zc,
	'reblandecer' => :er_c_zc,
	'reconocer' => :er_c_zc,
	'recrudecer' => :er_c_zc,
	'rejuvenecer' => :er_c_zc,
	'renacer' => :er_c_zc,
	'resplandecer' => :er_c_zc,
	'restablecer' => :er_c_zc,
	
	
	'ascender' => :er_e_ie,
	'atender' => :er_e_ie,
	'cerner' => :er_e_ie,
	'contender' => :er_e_ie,
	'encender' => :er_e_ie,
	'entender' => :er_e_ie,
	'extender' => :er_e_ie,
	'heder' => :er_e_ie,
	'hender' => :er_e_ie,
	'perder' => :er_e_ie,
	'tender' => :er_e_ie,
	'trascender' => :er_e_ie,
	'verter' => :er_e_ie,
	
	
	'defender' => :er_e_defender,
	'descender' => :er_e_defender,
	
	
	'desosar' => :er_o_hue,
	
	
	'absolver' => :er_o_ue,
	'condolerse' => :er_o_ue,
	'conmover' => :er_o_ue,
	'demoler' => :er_o_ue,
	'desenvolver' => :er_o_ue,
	'devolver' => :er_o_ue,
	'disolver' => :er_o_ue,
	'doler' => :er_o_ue,
	'dolerse' => :er_o_ue,
	'envolver' => :er_o_ue,
	'llover' => :er_o_ue,
	'moler' => :er_o_ue,
	'morder' => :er_o_ue,
	'mover' => :er_o_ue,
	'moverse' => :er_o_ue,
	'promover' => :er_o_ue,
	'remorder' => :er_o_ue,
	'remover' => :er_o_ue,
	'resolver' => :er_o_ue,
	'revolver' => :er_o_ue,
	'solver' => :er_o_ue,
	'volver' => :er_o_ue,
	
	
	'aberrar' => :ar_errar,
	'errar' => :ar_errar,
	
	
	'estar' => :ar_estar,
	
	
	'agraviar' => :ar_i_í,
	'agriar' => :ar_i_í,
	'ahijar' => :ar_i_í,
	'ahilar' => :ar_i_í,
	'ahitar' => :ar_i_í,
	'airar' => :ar_i_í,
	'aislar' => :ar_i_í,
	'aliar' => :ar_i_í,
	'amnistiar' => :ar_i_í,
	'amohinar' => :ar_i_í,
	'ampliar' => :ar_i_í,
	'ansiar' => :ar_i_í,
	'arriar' => :ar_i_í,
	'ataviar' => :ar_i_í,
	'atraillar' => :ar_i_í,
	'autografiar' => :ar_i_í,
	'averiar' => :ar_i_í,
	'aviar' => :ar_i_í,
	'baquiar' => :ar_i_í,
	'cablegrafiar' => :ar_i_í,
	'cariar' => :ar_i_í,
	'chirriar' => :ar_i_í,
	'ciar' => :ar_i_í,
	'cinematografiar' => :ar_i_í,
	'confiar' => :ar_i_í,
	'contrariar' => :ar_i_í,
	'criar' => :ar_i_í,
	'culiar' => :ar_i_í,
	'desafiar' => :ar_i_í,
	'desahijar' => :ar_i_í,
	'desainar' => :ar_i_í,
	'desairar' => :ar_i_í,
	'descafeinar' => :ar_i_í,
	'descarriar' => :ar_i_í,
	'desconfiar' => :ar_i_í,
	'desviar' => :ar_i_í,
	'enfriar' => :ar_i_í,
	'enviar' => :ar_i_í,
	'espiar' => :ar_i_í,
	'esquiar' => :ar_i_í,
	'estriar' => :ar_i_í,
	'expatriar' => :ar_i_í,
	'expiar' => :ar_i_í,
	'extraviar' => :ar_i_í,
	'fiar' => :ar_i_í,
	'fotografiar' => :ar_i_í,
	'guiar' => :ar_i_í,
	'hastiar' => :ar_i_í,
	'historiar' => :ar_i_í,
	'inventariar' => :ar_i_í,
	'liar' => :ar_i_í,
	'mimeografiar' => :ar_i_í,
	'paliar' => :ar_i_í,
	'piar' => :ar_i_í,
	'porfiar' => :ar_i_í,
	'prohijar' => :ar_i_í,
	'radiografiar' => :ar_i_í,
	'repatriar' => :ar_i_í,
	'resfriar' => :ar_i_í,
	'rociar' => :ar_i_í,
	'telegrafiar' => :ar_i_í,
	'vaciar' => :ar_i_í,
	'variar' => :ar_i_í,
	'xerografiar' => :ar_i_í,
	'zurriar' => :ar_i_í,
	
	
	'ahuchar' => :ar_u_ú,
	'ahuchear' => :ar_u_ú,
	'ahumar' => :ar_u_ú,
	'ahusar' => :ar_u_ú,
	'aullar' => :ar_u_ú,
	'aupar' => :ar_u_ú,
	'baraustar' => :ar_u_ú,
	'desahumar' => :ar_u_ú,
	'desbarahustar' => :ar_u_ú,
	'desembaular' => :ar_u_ú,
	'maular' => :ar_u_ú,
	'maullar' => :ar_u_ú,
	'parahusar' => :ar_u_ú,
	'parausar' => :ar_u_ú,
	'rehusar' => :ar_u_ú,
	'sahumar' => :ar_u_ú,
	'acensuar' => :ar_u_ú,
	'acentuar' => :ar_u_ú,
	'actuar' => :ar_u_ú,
	'arruar' => :ar_u_ú,
	'atenuar' => :ar_u_ú,
	'atumultuar' => :ar_u_ú,
	'avaluar' => :ar_u_ú,
	'colicuar' => :ar_u_ú,
	'conceptuar' => :ar_u_ú,
	'contextuar' => :ar_u_ú,
	'continuar' => :ar_u_ú,
	'desbruar' => :ar_u_ú,
	'descontinuar' => :ar_u_ú,
	'deshabituar' => :ar_u_ú,
	'desvaluar' => :ar_u_ú,
	'desvirtuar' => :ar_u_ú,
	'devaluar' => :ar_u_ú,
	'discontinuar' => :ar_u_ú,
	'efectuar' => :ar_u_ú,
	'enfatuarse' => :ar_u_ú,
	'estatuar' => :ar_u_ú,
	'evaluar' => :ar_u_ú,
	'exceptuar' => :ar_u_ú,
	'extenuar' => :ar_u_ú,
	'fluctuar' => :ar_u_ú,
	'perpetuar' => :ar_u_ú,
	'aunar' => :ar_u_ú,
	'puntuar' => :ar_u_ú,
	'adecuar' => :ar_u_ú,
	'graduar' => :ar_u_ú,
	'habituar' => :ar_u_ú,
	'insinuar' => :ar_u_ú,
	'licuar' => :ar_u_ú,
	'menstruar' => :ar_u_ú,
	'situar' => :ar_u_ú,
	'situarse' => :ar_u_ú,
	'valuar' => :ar_u_ú,
	
	
	'revolcar' => :car_o_ue,
  'trocar' => :car_o_ue,
  'volcar' => :car_o_ue,
  
  
  'colegir' => :egir,
	'corregir' => :egir,
	'elegir' => :egir,
	'reelegir' => :egir,
	'regir' => :egir,
	
	
	'atañer' => :er_atañer,
	
	
	'caber' => :er_caber,
	
	
	'caer' => :er_caer,
	'decaer' => :er_caer,
	'recaer' => :er_caer,
	
	
	'haber' => :er_haber,
	
	
	'contrahacer' => :er_hacer,
	'deshacer' => :er_hacer,
	'hacer' => :er_hacer,
	'hacer caso' => :er_hacer,
	'hacer cosquillas' => :er_hacer,
	'hacer novillos' => :er_hacer,
	'rehacer' => :er_hacer,
	'satisfacer' => :er_hacer,
	
	
	'placer' => :er_placer,
	'complacer' => :er_placer,
	
	
	'poder' => :er_poder,
	
	
	'anteponer' => :er_poner,
	'aponer' => :er_poner,
	'componer' => :er_poner,
	'contraponer' => :er_poner,
	'deponer' => :er_poner,
	'descomponer' => :er_poner,
	'disponer' => :er_poner,
	'exponer' => :er_poner,
	'imponer' => :er_poner,
	'indisponer' => :er_poner,
	'interponer' => :er_poner,
	'oponer' => :er_poner,
	'oponerse' => :er_poner,
	'poner' => :er_poner,
	'ponerse' => :er_poner,
	'ponerse a' => :er_poner,
	'posponer' => :er_poner,
	'predisponer' => :er_poner,
	'presuponer' => :er_poner,
	'proponer' => :er_poner,
	'reponer' => :er_poner,
	'sobreponer' => :er_poner,
	'superponer' => :er_poner,
	'suponer' => :er_poner,
	'yuxtaponer' => :er_poner,
	
	
	'querer' => :er_querer,
	'bienquerer' => :er_querer, 
	'malquerer' => :er_querer,
	
	
	'raer' => :er_raer,
	
	
	'rehacer' => :er_rehacer,
	
	
	'roer' => :er_roer,
	'corroer' => :er_roer,
	
	
	'resaber' => :er_saber,
  'saber' => :er_saber,
  
  
  'ser' => :er_ser,
  
	
	'soler' => :er_soler,
	
	
	'abstenerse' => :er_tener,
	'abstener' => :er_tener,
	'atener' => :er_tener,
	'atenerse' => :er_tener,
	'contener' => :er_tener,
	'detener' => :er_tener,
	'detenerse' => :er_tener,
	'entretener' => :er_tener,
	'mantener' => :er_tener,
	'obtener' => :er_tener,
	'retener' => :er_tener,
	'sostener' => :er_tener,
	'tener' => :er_tener,
	'tener que' => :er_tener,
	
	
	'abstraer' => :er_traer,
	'atraer' => :er_traer,
	'contraer' => :er_traer,
	'distraer' => :er_traer,
	'extraer' => :er_traer,
	'retraer' => :er_traer,
	'retraerse' => :er_traer,
	'substraer' => :er_traer,
	'sustraer' => :er_traer,
	'traer' => :er_traer,
	
	
	'equivaler' => :er_valer,
  'valer' => :er_valer,
  'prevalerse' => :er_valer,
  
  'ver' => :er_ver,
  
  'antever' => :er_prever,
	'entrever' => :er_prever,
	'prever' => :er_prever,
	'verse' => :er_prever,
	'trasver' => :er_prever,
	'rever' => :er_prever,
	
	
	'yacer' => :er_yacer,
	'subyacer' => :er_yacer,
	
	
	'desleír' => :eír,
	'engreír' => :eír,
	'esleír' => :eír,
	'freír' => :eír,
	'refreír' => :eír,
	'reír' => :eír,
	'sofreír' => :eír,
	'sonreír' => :eír,
	
	
	'jugar' => :gar_u_ue,
	
	
	'adaguar' => :guar,
	'aguar' => :guar,
	'amenguar' => :guar,
	'amortiguar' => :guar,
	'antiguar' => :guar,
	'apaciguar' => :guar,
	'apaciguarse' => :guar,
	'apaniguar' => :guar,
	'atestiguar' => :guar,
	'atreguar' => :guar,
	'averiguar' => :guar,
	'desaguar' => :guar,
	'deslenguar' => :guar,
	'deslenguarse' => :guar,
	'fraguar' => :guar,
	'menguar' => :guar,
	'testiguar' => :guar,
	
	
	'abolir' => :ir_abolir,
  'agredir' => :ir_abolir,
  'aterirse' => :ir_abolir,
  
  'asir' => :ir_asir,
  'desasir' => :ir_asir,
  
  
  'aterir' => :aterir,
  'aterirse' => :aterir,
  'garantir' => :aterir,
  'transgredir' => :aterir,
  
  
  'antedecir' => :ir_decir,
	'bendecir' => :ir_decir,
	'condecir' => :ir_decir,
	'contradecir' => :ir_decir,
	'decir' => :ir_decir,
	'desdecir' => :ir_decir,
	'interdecir' => :ir_decir,
	'maldecir' => :ir_decir,
	'predecir' => :ir_decir,
	'redecir' => :ir_decir,
	
	
	'cernir' => :ir_e_ie,
  'concernir' => :ir_e_ie,
  'discernir' => :ir_e_ie,
  
  
  'embaír' => :ir_embaír,
  'desvaír' => :ir_embaír,
  
  
  'erguir' => :ir_erguir,
  
  
	'adquirir' => :ir_i_ie,
	'inquirir' => :ir_i_ie,
	'perquirir' => :ir_i_ie,
	'coadquirir' => :ir_i_ie,
	
	
	'ir' => :ir_ir,
	
	
	'dormir' => :ir_o_ue,
	'morir' => :ir_o_ue,
	
	
	'oír' => :ir_oír,
	'entreoír' => :ir_oír,
	
	
	'rehuir' => :ir_rehuir,
	
	
	'salir' => :ir_salir,
	'sobresalir' => :ir_salir,
	
	
	'advenir' => :ir_venir,
	'avenir' => :ir_venir,
	'circunvenir' => :ir_venir,
	'contravenir' => :ir_venir,
	'convenir' => :ir_venir,
	'devenir' => :ir_venir,
	'entrevenir' => :ir_venir,
	'intervenir' => :ir_venir,
	'prevenir' => :ir_venir,
	'provenir' => :ir_venir,
	'revenirse' => :ir_venir,
	'venir' => :ir_venir,
	'sobrevenir' => :ir_venir,
	
	
	'enraizar' => :izar,
  'homogeneizar' => :izar,
  
  
  'tañer' => :ñer,
  'atañer' => :ñer,
  'empeller' => :ñer,
  
  
  'abnegar' => :gar,
	'abogar' => :gar,
	'abrigar' => :gar,
	'abrogar' => :gar,
	'agregar' => :gar,
	'ahogar' => :gar,
	'alargar' => :gar,
	'albergar' => :gar,
	'alegar' => :gar,
	'amagar' => :gar,
	'amargar' => :gar,
	'antepagar' => :gar,
	'apagar' => :gar,
	'apagarse' => :gar,
	'arengar' => :gar,
	'arraigar' => :gar,
	'arriesgar' => :gar,
	'arrogar' => :gar,
	'arrogarse' => :gar,
	'arrugar' => :gar,
	'atosigar' => :gar,
	'bregar' => :gar,
	'cabalgar' => :gar,
	'cagar' => :gar,
	'cargar' => :gar,
	'castigar' => :gar,
	'catalogar' => :gar,
	'centrifugar' => :gar,
	'chingar' => :gar,
	'circunnavegar' => :gar,
	'comulgar' => :gar,
	'congregar' => :gar,
	'conjugar' => :gar,
	'corrugar' => :gar,
	'delegar' => :gar,
	'derogar' => :gar,
	'desahogar' => :gar,
	'desarraigar' => :gar,
	'descargar' => :gar,
	'descomulgar' => :gar,
	'desligar' => :gar,
	'despegar' => :gar,
	'disgregar' => :gar,
	'divagar' => :gar,
	'divulgar' => :gar,
	'dragar' => :gar,
	'drogar' => :gar,
	'embragar' => :gar,
	'embriagar' => :gar,
	'encargar' => :gar,
	'endrogarse' => :gar,
	'enjalbegar' => :gar,
	'enjuagar' => :gar,
	'enjugar' => :gar,
	'entregar' => :gar,
	'estragar' => :gar,
	'estregar' => :gar,
	'excomulgar' => :gar,
	'fatigar' => :gar,
	'fugar' => :gar,
	'fugarse' => :gar,
	'fustigar' => :gar,
	'halagar' => :gar,
	'homologar' => :gar,
	'hostigar' => :gar,
	'hurgar' => :gar,
	'indagar' => :gar,
	'instigar' => :gar,
	'interrogar' => :gar,
	'intrigar' => :gar,
	'investigar' => :gar,
	'irrigar' => :gar,
	'irrogar' => :gar,
	'jeringar' => :gar,
	'juzgar' => :gar,
	'largar' => :gar,
	'legar' => :gar,
	'levigar' => :gar,
	'ligar' => :gar,
	'litigar' => :gar,
	'llegar' => :gar,
	'logar' => :gar,
	'madrugar' => :gar,
	'mendigar' => :gar,
	'mitigar' => :gar,
	'naufragar' => :gar,
	'navegar' => :gar,
	'obligar' => :gar,
	'otorgar' => :gar,
	'pagar' => :gar,
	'pegar' => :gar,
	'pegarse' => :gar,
	'plagar' => :gar,
	'postergar' => :gar,
	'prolongar' => :gar,
	'promulgar' => :gar,
	'propagar' => :gar,
	'prorrogar' => :gar,
	'purgar' => :gar,
	'rasgar' => :gar,
	'recargar' => :gar,
	'remangar' => :gar,
	'ringar' => :gar,
	'segregar' => :gar,
	'singar' => :gar,
	'sobrecargar' => :gar,
	'sojuzgar' => :gar,
	'sufragar' => :gar,
	'tragar' => :gar,
	'vagar' => :gar,
	'vengar' => :gar,
	'prejuzgar' => :gar,
	'pringar' => :gar,
	'prodigar' => :gar,
	
	
	'anegar' => :gar_e_ie,
	'cegar' => :gar_e_ie,
	'denegar' => :gar_e_ie,
	'desasosegar' => :gar_e_ie,
	'desplegar' => :gar_e_ie,
	'fregar' => :gar_e_ie,
	'negar' => :gar_e_ie,
	'plegar' => :gar_e_ie,
	'regar' => :gar_e_ie,
	'renegar' => :gar_e_ie,
	'replegar' => :gar_e_ie,
	'restregar' => :gar_e_ie,
	'segar' => :gar_e_ie,
	'sosegar' => :gar_e_ie,
	
	
	'alongar' => :gar_o_ue,
	'colgar' => :gar_o_ue,
	'descolgar' => :gar_o_ue,
	'holgar' => :gar_o_ue,
	'rogar' => :gar_o_ue,
	
	
	'acoger' => :ger,
	'coger' => :ger,
	'deterger' => :ger,
	'emerger' => :ger,
	'encoger' => :ger,
	'escoger' => :ger,
	'proteger' => :ger,
	'recoger' => :ger,
	'sobrecoger' => :ger,
	
	
	'afligir' => :gir,
	'astringir' => :gir,
	'convergir' => :gir,
	'dirigir' => :gir,
	'dirigirse' => :gir,
	'erigir' => :gir,
	'exigir' => :gir,
	'fingir' => :gir,
	'infligir' => :gir,
	'infringir' => :gir,
	'mugir' => :gir,
	'redirigir' => :gir,
	'restringir' => :gir,
	'rugir' => :gir,
	'sumergir' => :gir,
	'surgir' => :gir,
	'ungir' => :gir,
	'urgir' => :gir,
	
	
	'distinguir' => :guir,
	'extinguir' => :guir,
	
	
	'conseguir' => :guir_e_i,
	'perseguir' => :guir_e_i,
	'proseguir' => :guir_e_i,
	'seguir' => :guir_e_i,
	'subseguir' => :guir_e_i,
	
	
	'argüir' => :güir,
	'reargüir' => :güir,
	'redargüir' => :güir,
	
	
	'ahincar' => :car_i_í,
	
	
	'cabrahigar' => :gar_i_í,
	
	
	'acuantiar' => :iar_ar,
	'afiliar' => :iar_ar,
	'auxiliar' => :iar_ar,
	'extasiar' => :iar_ar,
	'gloriar' => :iar_ar,
	'vanagloriar' => :iar_ar,
	
	
	'balbucir' => :ir_c_zc,
	'deslucir' => :ir_c_zc,
	'enlucir' => :ir_c_zc,
	'lucir' => :ir_c_zc,
	'relucir' => :ir_c_zc,
	'reproducirse' => :ir_c_zc,
	'traslucirse' => :ir_c_zc,
	
	
	'competir' => :ir_e_i,
	'concebir' => :ir_e_i,
	'derretir' => :ir_e_i,
	'despedir' => :ir_e_i,
	'despedirse' => :ir_e_i,
	'desvestir' => :ir_e_i,
	'embestir' => :ir_e_i,
	'expedir' => :ir_e_i,
	'gemir' => :ir_e_i,
	'impedir' => :ir_e_i,
	'medir' => :ir_e_i,
	'pedir' => :ir_e_i,
	'reexpedir' => :ir_e_i,
	'rendir' => :ir_e_i,
	'repetir' => :ir_e_i,
	'revestir' => :ir_e_i,
	'servir' => :ir_e_i,
	'trasgredir' => :ir_e_i,
	'vestir' => :ir_e_i,
	'vestirse' => :ir_e_i,
	'preconcebir' => :ir_e_i,
	
	
	'adherir' => :ir_e_ie_i,
	'advertir' => :ir_e_ie_i,
	'arrepentir' => :ir_e_ie_i,
	'asentir' => :ir_e_ie_i,
	'conferir' => :ir_e_ie_i,
	'consentir' => :ir_e_ie_i,
	'controvertir' => :ir_e_ie_i,
	'convertir' => :ir_e_ie_i,
	'convertirse' => :ir_e_ie_i,
	'diferir' => :ir_e_ie_i,
	'digerir' => :ir_e_ie_i,
	'disentir' => :ir_e_ie_i,
	'divertir' => :ir_e_ie_i,
	'divertirse' => :ir_e_ie_i,
	'herir' => :ir_e_ie_i,
	'hervir' => :ir_e_ie_i,
	'inferir' => :ir_e_ie_i,
	'ingerir' => :ir_e_ie_i,
	'interferir' => :ir_e_ie_i,
	'invertir' => :ir_e_ie_i,
	'malherir' => :ir_e_ie_i,
	'mentir' => :ir_e_ie_i,
	'pervertir' => :ir_e_ie_i,
	'preferir' => :ir_e_ie_i,
	'presentir' => :ir_e_ie_i,
	'proferir' => :ir_e_ie_i,
	'reconvertir' => :ir_e_ie_i,
	'referir' => :ir_e_ie_i,
	'referirse' => :ir_e_ie_i,
	'requerir' => :ir_e_ie_i,
	'revertir' => :ir_e_ie_i,
	'sentir' => :ir_e_ie_i,
	'sentirse' => :ir_e_ie_i,
	'sugerir' => :ir_e_ie_i,
	'transferir' => :ir_e_ie_i,
	'zaherir' => :ir_e_ie_i,
	
	
	'desmentir' => :ir_desmentir,
	
	
	'prohibir' => :ir_i_í,
	'cohibir' => :ir_i_í,
	
	
	'reunir' => :ir_u_ú,
	
	
	'delinquir' => :quir,
	'derelinquir' => :quir,
	'jaquir' => :quir,
	
	
	'afluir' => :uir,
	'atribuir' => :uir,
	'autodestruir' => :uir,
	'circuir' => :uir,
	'concluir' => :uir,
	'confluir' => :uir,
	'constituir' => :uir,
	'construir' => :uir,
	'contribuir' => :uir,
	'destituir' => :uir,
	'destruir' => :uir,
	'diluir' => :uir,
	'disminuir' => :uir,
	'distribuir' => :uir,
	'excluir' => :uir,
	'fluir' => :uir,
	'huir' => :uir,
	'incluir' => :uir,
	'influir' => :uir,
	'inmiscuirse' => :uir,
	'instituir' => :uir,
	'instruir' => :uir,
	'obstruir' => :uir,
	'prostituir' => :uir,
	'recluir' => :uir,
	'reconstruir' => :uir,
	'restituir' => :uir,
	'sustituir' => :uir,
	
	
	'abalanzar' => :zar,
	'abrazar' => :zar,
	'acorazar' => :zar,
	'actualizar' => :zar,
	'adelgazar' => :zar,
	'adelgazarse' => :zar,
	'aderezar' => :zar,
	'afianzar' => :zar,
	'agilizar' => :zar,
	'agonizar' => :zar,
	'agudizar' => :zar,
	'aguzar' => :zar,
	'alcanzar' => :zar,
	'alfabetizar' => :zar,
	'alzar' => :zar,
	'amenazar' => :zar,
	'amenizar' => :zar,
	'americanizar' => :zar,
	'amordazar' => :zar,
	'amortizar' => :zar,
	'analizar' => :zar,
	'anarquizar' => :zar,
	'antagonizar' => :zar,
	'aplazar' => :zar,
	'atemorizar' => :zar,
	'atenazar' => :zar,
	'aterrizar' => :zar,
	'aterrorizar' => :zar,
	'atizar' => :zar,
	'atomizar' => :zar,
	'automatizar' => :zar,
	'autorizar' => :zar,
	'avanzar' => :zar,
	'avezar' => :zar,
	'azuzar' => :zar,
	'barbarizar' => :zar,
	'barnizar' => :zar,
	'bautizar' => :zar,
	'bostezar' => :zar,
	'brutalizar' => :zar,
	'calzar' => :zar,
	'canalizar' => :zar,
	'caracterizar' => :zar,
	'carbonizar' => :zar,
	'catalizar' => :zar,
	'catolizar' => :zar,
	'cauterizar' => :zar,
	'cazar' => :zar,
	'centralizar' => :zar,
	'cicatrizar' => :zar,
	'civilizar' => :zar,
	'climatizar' => :zar,
	'cloroformizar' => :zar,
	'colonizar' => :zar,
	'conceptualizar' => :zar,
	'concretizar' => :zar,
	'contextualizar' => :zar,
	'cotizar' => :zar,
	'cristalizar' => :zar,
	'cristianizar' => :zar,
	'cruzar' => :zar,
	'danzar' => :zar,
	'democratizar' => :zar,
	'desautorizar' => :zar,
	'descabezar' => :zar,
	'descalzar' => :zar,
	'descentralizar' => :zar,
	'descortezar' => :zar,
	'desensibilizar' => :zar,
	'desertizar' => :zar,
	'desguazar' => :zar,
	'deshumanizar' => :zar,
	'desionizar' => :zar,
	'deslizar' => :zar,
	'desnaturalizar' => :zar,
	'desorganizar' => :zar,
	'despedazar' => :zar,
	'desperezarse' => :zar,
	'despiezar' => :zar,
	'desplazar' => :zar,
	'destrozar' => :zar,
	'diagonalizar' => :zar,
	'digitalizar' => :zar,
	'disfrazar' => :zar,
	'dramatizar' => :zar,
	'economizar' => :zar,
	'electrizar' => :zar,
	'embarazar' => :zar,
	'encabezar' => :zar,
	'enderezar' => :zar,
	'endulzar' => :zar,
	'enfatizar' => :zar,
	'enlazar' => :zar,
	'entrelazar' => :zar,
	'esbozar' => :zar,
	'escandalizar' => :zar,
	'especializar' => :zar,
	'esperanzar' => :zar,
	'esquematizar' => :zar,
	'estabilizar' => :zar,
	'esterilizar' => :zar,
	'evangelizar' => :zar,
	'exorcizar' => :zar,
	'familiarizar' => :zar,
	'fertilizar' => :zar,
	'finalizar' => :zar,
	'fiscalizar' => :zar,
	'formalizar' => :zar,
	'fosilizarse' => :zar,
	'fraternizar' => :zar,
	'galvanizar' => :zar,
	'garantizar' => :zar,
	'gargarizar' => :zar,
	'generalizar' => :zar,
	'germanizar' => :zar,
	'globalizar' => :zar,
	'gozar' => :zar,
	'granizar' => :zar,
	'hechizar' => :zar,
	'helenizar' => :zar,
	'hipnotizar' => :zar,
	'hospitalizar' => :zar,
	'hozar' => :zar,
	'humanizar' => :zar,
	'idealizar' => :zar,
	'ilegalizar' => :zar,
	'indemnizar' => :zar,
	'independizarse' => :zar,
	'indizar' => :zar,
	'industrializar' => :zar,
	'inmortalizar' => :zar,
	'inmovilizar' => :zar,
	'inmunizar' => :zar,
	'insensibilizar' => :zar,
	'internacionalizar' => :zar,
	'inutilizar' => :zar,
	'ionizar' => :zar,
	'ironizar' => :zar,
	'izar' => :zar,
	'jerarquizar' => :zar,
	'laicizar' => :zar,
	'lanzar' => :zar,
	'lazar' => :zar,
	'legalizar' => :zar,
	'localizar' => :zar,
	'matizar' => :zar,
	'maximizar' => :zar,
	'memorizar' => :zar,
	'mercerizar' => :zar,
	'metalizar' => :zar,
	'metastatizar' => :zar,
	'militarizar' => :zar,
	'mimetizar' => :zar,
	'minimizar' => :zar,
	'modernizar' => :zar,
	'monopolizar' => :zar,
	'moralizar' => :zar,
	'movilizar' => :zar,
	'nacionalizar' => :zar,
	'naturalizar' => :zar,
	'neutralizar' => :zar,
	'nominalizar' => :zar,
	'normalizar' => :zar,
	'occidentalizar' => :zar,
	'oficializar' => :zar,
	'optimizar' => :zar,
	'organizar' => :zar,
	'paralizar' => :zar,
	'pasterizar' => :zar,
	'pasteurizar' => :zar,
	'penalizar' => :zar,
	'personalizar' => :zar,
	'polarizar' => :zar,
	'popularizar' => :zar,
	'potabilizar' => :zar,
	'priorizar' => :zar,
	'privatizar' => :zar,
	'profesionalizar' => :zar,
	'profetizar' => :zar,
	'profundizar' => :zar,
	'protagonizar' => :zar,
	'psicoanalizar' => :zar,
	'pulverizar' => :zar,
	'punzar' => :zar,
	'racionalizar' => :zar,
	'realizar' => :zar,
	'realzar' => :zar,
	'rebozar' => :zar,
	'rechazar' => :zar,
	'reemplazar' => :zar,
	'reorganizar' => :zar,
	'retozar' => :zar,
	'reutilizar' => :zar,
	'rezar' => :zar,
	'ridiculizar' => :zar,
	'rivalizar' => :zar,
	'rizar' => :zar,
	'romanizar' => :zar,
	'romanzar' => :zar,
	'ronzar' => :zar,
	'nacionalizar' => :zar,
	'narcotizar' => :zar,
	'obstaculizar' => :zar,
	'particularizar' => :zar,
	'polimerizar' => :zar,
	'polinizar' => :zar,
	'pormenorizar' => :zar,
	'prconizar' => :zar,
	'presuizar' => :zar,
	'puntualizar' => :zar,
	'utilizar' => :zar,
	'trazar' => :zar,
	
	
	'comenzar' => :zar_e_ie,
	'despezar' => :zar_e_ie,
	'empezar' => :zar_e_ie,
	'enlenzar' => :zar_e_ie,
	'entropezar' => :zar_e_ie,
	'recomenzar' => :zar_e_ie,
	'tropezar' => :zar_e_ie,
	
	
	'avergonzar' => :zar_go_güe,
	'avergonzarse' => :zar_go_güe,
	'envergonzar' => :zar_go_güe,
	'desvergonzar' => :zar_go_güe,
	'desvergonzarse' => :zar_go_güe,
	
	
	'almorzar' => :zar_o_ue,
	'desforzar' => :zar_o_ue,
	'esforzar' => :zar_o_ue,
	'forzar' => :zar_o_ue,
	'reforzar' => :zar_o_ue,
	
	
	'bruñir' => :ñir,
	'bullir' => :ñir,
	'engullir' => :ñir,
	'fuñir' => :ñir,
	'gañir' => :ñir,
	'gruñir' => :ñir,
	'mullir' => :ñir,
	'muñir' => :ñir,
	'plañir' => :ñir,
	'rebullir' => :ñir,
	'zabullir' => :ñir,
	'zambullir' => :ñir,
	'zambullirse' => :ñir,
	
	
	'astreñir' => :ñir_e_i,
	'ceñir' => :ñir_e_i,
	'constreñir' => :ñir_e_i,
	'desteñir' => :ñir_e_i,
	'estreñir' => :ñir_e_i,
	'heñir' => :ñir_e_i,
	'reteñir' => :ñir_e_i,
	'reñir' => :ñir_e_i,
	'teñir' => :ñir_e_i
	
	
	
	
}




